version: '3.3'
services:
  nginx:
    image: tutum/nginx
    ports:
        - "80:80"
    links:
        - phpfpm1
        - phpfpm2
        - phpfpm3
    volumes:
        - ./nginx/default:/etc/nginx/sites-available/
        - ./nginx/default:/etc/nginx/sites-enabled/
        - ./logs/nginx-error.log:/var/log/nginx/error.log
        - ./logs/nginx-access.log:/var/log/nginx/access.log
  phpfpm1:
    image: 'php:fpm'
    restart: always
    ports:
      - '9000'
    volumes:
      - './source:/usr/share/nginx/html'
  phpfpm2:
    image: 'php:fpm'
    restart: always
    ports:
      - '9000'
    volumes:
      - './source:/usr/share/nginx/html'
  phpfpm3:
    image: 'php:fpm'
    restart: always
    ports:
      - '9000'
    volumes:
      - './source:/usr/share/nginx/html'
  maria:
    image: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: admin
    volumes:
      - './database/maria:/var/lib/mysql'
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: always
    links:
      - maria
    ports:
      - '8080:80'
    environment:
      MYSQL_USERNAME: nam
      MYSQL_ROOT_PASSWORD: nam
      PMA_ARBITRARY: 1
